apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: hadoop-slave
  name: hadoop-slave-controller
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: hadoop-slave
    spec:
      hostname: hadoop-slave
      containers:
      - image: georgek42/armhf-hadoop
        name: master
        stdin: true
        tty: true
        ports:
          - containerPort: 22
          - containerPort: 3000
          - containerPort: 3001
          - containerPort: 3002
          - containerPort: 3003
          - containerPort: 3004
          - containerPort: 3005
          - containerPort: 3006
          - containerPort: 3007
          - containerPort: 3008
          - containerPort: 8040
          - containerPort: 8042
          - containerPort: 13562
          - containerPort: 50010
          - containerPort: 50020
          - containerPort: 50075
        env:
          - name: MASTER_HOSTNAME
            value: "hadoop-master"
