apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: hadoop-master
  name: hadoop-master-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hadoop-master
    spec:
      hostname: hadoop-master
      containers:
      - image: georgek42/armhf-hadoop
        name: master
        stdin: true
        tty: true
        ports:
          - name: hadoop
            containerPort: 50070
            hostPort: 50070
          - name: hadoop2
            containerPort: 8088
            hostPort: 8088
          - name: hdfs
            containerPort: 9000
            hostPort: 9000
          - name: ssh
            containerPort: 22
            hostPort: 22
        env:
          - name: IMAMASTER
            value: "true"
