apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: hadoop-slave2
  name: hadoop-slave2-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hadoop-slave2
    spec:
      hostname: hadoop-slave2
      containers:
      - image: georgek42/armhf-hadoop
        name: master
        stdin: true
        tty: true
        ports:
          - name: hadoop
            containerPort: 50070
            hostPort: 50070
          - name: hadoop3000
            containerPort: 3000
            hostPort: 3000
          - name: hadoop3001
            containerPort: 3001
            hostPort: 3001
          - name: hadoop3002
            containerPort: 3002
            hostPort: 3002
          - name: hadoop3003
            containerPort: 3003
            hostPort: 3003
          - name: hadoop3004
            containerPort: 3004
            hostPort: 3004
          - name: hadoop3005
            containerPort: 3005
            hostPort: 3005
          - name: hadoop3006
            containerPort: 3006
            hostPort: 3006
          - name: hadoop3007
            containerPort: 3007
            hostPort: 3007
          - name: hadoop3008
            containerPort: 3008
            hostPort: 3008
          - name: hadoop2
            containerPort: 8088
            hostPort: 8088
          - name: hadoop3
            containerPort: 8040
            hostPort: 8040
          - name: hadoop4
            containerPort: 8042
            hostPort: 8042
          - name: hadoop5
            containerPort: 13562
            hostPort: 13562
          - name: datanode
            containerPort: 50010
            hostPort: 50010
          - name: datanode2
            containerPort: 50020
            hostPort: 50020
          - name: datanode3
            containerPort: 50075
            hostPort: 50075
          - name: hdfs
            containerPort: 9000
            hostPort: 9000
          - name: ssh
            containerPort: 22
            hostPort: 22
        env:
          - name: MASTER_HOSTNAME
            value: "hadoop-master"
