apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: hadoop-master
  name: hadoop-master-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hadoop-master
    spec:
      hostname: hadoop-master
      containers:
      - image: georgek42/armhf-hadoop
        name: master
        stdin: true
        tty: true
        ports:
          - containerPort: 22
          - containerPort: 3000
          - containerPort: 3001
          - containerPort: 3002
          - containerPort: 3003
          - containerPort: 3004
          - containerPort: 3005
          - containerPort: 3006
          - containerPort: 3007
          - containerPort: 3008
          - containerPort: 8030
          - containerPort: 8031
          - containerPort: 8032
          - containerPort: 8033
          - containerPort: 8088
          - containerPort: 9000
          - containerPort: 50070
          - containerPort: 50090
        env:
          - name: IMAMASTER
            value: "true"
